### PR TITLE
hide remove command

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by dickeyxxx** [comment]
cc @heroku/ecosystem 

this just hides the command from `heroku help addons`

**Comment by mathias** [comment]
I'm trying to remember the context here. If we hide `addons:destroy`, then what will customers use in the CLI to remove an add-on?

**Comment by dickeyxxx** [comment]
this hides `addons:remove`, not `addons:destroy`. Both will still work, this just makes it so `addons:remove` isn't visible in help. Which I think matches how we suggest users interact with add-ons.

**Comment by mathias** [comment]
Aha, I see the difference in the two lines in the diff now. Thanks for clarifying!

**Comment by mathias** [comment]
This LGTM.

**Comment by geemus** [comment]
👍  I think there are good places to do add/remove, but this seems like a clear create/destroy.

**Pull request merged**
