### PR TITLE
added code coverage

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by bjeanes** [comment]
I don't totally understand where to *view* the coverage so some clarity there would be good, but this seems fine.

**Comment by dickeyxxx** [comment]
it's on the README

**Comment by bjeanes** [comment]
@dickeyxxx the coverage *percentage* is, but not the actual LOC covered.

**Comment by dickeyxxx** [comment]
maybe I'm confused but this? https://coveralls.io/builds/5775802

**Comment by bjeanes** [comment]
Nope, I'm just an idiot. I was just expecting a commit status or something that linked to that or an artefact in the CircleCI build. All good... thanks!

**Pull request merged**
