### PR TITLE
fix = in addons:create flags

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by ransombriggs** [comment]
@dickeyxxx I do not think this code will work in the following case `--foo=bar=biz` I think it would set `foo` to `bar` rather than `bar=biz` if I am reading the code correctly

**Comment by ransombriggs** [comment]
@dickeyxxx also, you should probably not args.shift due to other related issue

**Comment by dickeyxxx** [comment]
The shift is okay here because I call .slice on the array before sending it in, which clones the array

**Comment by ransombriggs** [comment]
@dickeyxxx good point on the args slice, could you throw in a test for `--foo=--bar`?  I think this would set `foo` and `bar` to `true` rather than `foo` to `--bar`

**Comment by ransombriggs** [comment]
@dickeyxxx lgtm

**Pull request merged**
