### PR TITLE
updated heroku-cli-util

### PR DESCRIPTION
**Pull request by dickeyxxx**
* used cli.table from heroku-cli-util
* locked all dependencies down

### CODE REVIEW

**Comment by dickeyxxx** [comment]
@bjeanes this is going to go into the productionization guide @ransombriggs and I are working on this quarter, but one requirement is going to be to lock the dependencies down. We always try to follow semver, of course, but without locking them down the clients would autoupdate to the newest patch release. We've had issues in the past where a change was put in that had a bug, or really required a major bump instead. This ensures that doesn't happen.

**Comment by bjeanes** [comment]
Makes sense! Did you make any changes to the table fn that would warrant in-depth testing here or is it pretty much just a copy paste at this point?

**Comment by dickeyxxx** [comment]
I'm a little confused what you're asking. Wouldn't tests related to the table output go into `heroku-cli-util` and not `heroku-cli-addons`? Or is that what you're asking?

**Comment by bjeanes** [comment]
@dickeyxxx I'm asking if there's any reason I need to pull this down, switch to the branch and test it, i.e.if the vendored version of table that you're removing is out of date. If it's unchanged, then I think just merging this is fine, given the tests still pass.

**Comment by dickeyxxx** [comment]
Ah yeah it's unchanged

**Comment by bjeanes** [comment]
Alright 60be3312f432041c0eb78f1fcd35ffcdaa4ec82c shipped as 0.1.1

@dickeyxxx does this subsume #9, given your dependency lockdown herein?

**Pull request merged**
