### PR TITLE
Allow --url to be passed to addons:open to only print the URL

### PR DESCRIPTION
**Pull request by mathias**
@dickeyxxx This follows on your work on the docs command and what I was thinking for `addons:open`. 

Let me know if there's supposed to be a different convention for initializing a var with a `let` as I've done on https://github.com/heroku/heroku-cli-addons/commit/0a9648b9fcf8b2248467884fb8697f2557b642ef#diff-3596c35865477ab6adf2eaa5ebc70c20R68

Thanks!

### CODE REVIEW

**Comment by dickeyxxx** [comment]
lgtm!

**Comment by dickeyxxx** [comment]
var is fine, but you should read up on variable hoisting if you're curious why I use let

**Comment by bjeanes** [comment]
One about `--print` or something. When I first saw the PR title I thought this did something else.

**Comment by dickeyxxx** [comment]
I like --url, to me that's what it does, it shows the url

**Comment by dickeyxxx** [comment]
--print seems less obvious somehow

**Comment by bjeanes** [comment]
> that's what it does, it shows the url

Then `--show-url` seems most appropriate. `--url` implies it takes a `URL` parameter to me.

**Comment by dickeyxxx** [comment]
I'm fine with `--show-url`. I'll update the other PR

**Comment by mathias** [comment]
Updated this with the `docs` branch that it is targeted at.

**Comment by bjeanes** [comment]
Looks like this needs a rebase and to have the `open` command match `docs` by using `--show-url` as discussed above.

**Comment by mathias** [comment]
Closing this to open a new PR targeted at master, based off of master.

**Comment by mathias** [comment]
Closing this since #20 is merged, to open a new PR that is aimed at merging to master.

**Pull request closed without merging**
