### PR TITLE
export resolver

### PR DESCRIPTION
**Pull request by dickeyxxx**
DoD can make use of this to find add-ons in their plugins.

### CODE REVIEW

**Comment by dickeyxxx** [comment]
cc @tcrayford

**Comment by tcrayford** [comment]
@dickeyxxx will this take care of all the things we want?

- resolving via addon name (`kafka-globulated-discworld-98345`)
- resolving the only addon on an app if we have an app (``)
- resolving the named addon without an app supplied to the cli if the name is globally unique (`kakfa-globulated-discworld-98345`)
- resolving via config var (e.g. `HEROKU_KAFKA_BROWN_URL`)
- resolving via attachment (e.g. `HEROKU_KAFKA_BROWN`)
- resolving via short `addon::color` (e.g. `heroku-kafka::brown`)

I guess we'll need to change `needsApp` to `wantsApp`?

ccing @uhoh-itsmaciek on this one, because the Data UX team is taking over the DoD CLI plugins.

**Comment by uhoh-itsmaciek** [comment]
+1 to that list, although I don't think the first and third case are distinct: the haiku names for *active* addons within a single cloud *are* unique. That is, someone else can have `kafka-globulated-discworld-98345` in their staging, and someone else may get `kafka-globulated-discworld-98345` if you deprovision yours, but other than that there should be no collision.

Also, can you point us to usage examples?

**Comment by uhoh-itsmaciek** [comment]
Hmm, actually I suppose there *is* a distinction here that @tcrayford hinted at: for many of our commands, if the user passes in something globally unique like the haiku name, the app is superfluous. It'd be nice to have that as an optional argument for those cases, but I guess that gets tricky.

**Comment by dickeyxxx** [comment]
I think it will handle all of those actually. Not 100% sure on the config vars, but I think it will just because the API will expect all those. If the app is nil it won't try to look up based on app context.

**Comment by dickeyxxx** [comment]
Testing it out a bit, I think it does work for everything you mentioned.

You can test it with `heroku addons:open NAMEOFTHING` (which uses this logic) with an optional app to see if it matches everything you expect.

**Comment by dickeyxxx** [comment]
the code is pretty straightforward to use it too I think https://github.com/heroku/heroku-cli-addons/blob/master/commands/addons/open.js#L67-L74

**Comment by uhoh-itsmaciek** [comment]
Awesome, I'll take a look at integrating that into our kafka CLI plugin as a starting point.

**Comment by dickeyxxx** [comment]
I do like this concept in theory, since we could make the addons lookups consistent across all commands and make any needed changes/bug fixes in one place. We haven't done this before, but I think it sets a good pattern. This is a great place to start since the resolving code is super complicated to comprehend and quite a few people have already written and reviewed different parts of it.

**Comment by bjeanes** [comment]
@tcrayford @uhoh-itsmaciek it should handle all those cases because they are handled [in the API itself](https://github.com/heroku/api/blob/master/lib/api/mediators/addons/resolver.rb).

**Comment by uhoh-itsmaciek** [comment]
@bjeanes that's only provisioning, no? I think this is for resolving for other commands like `pg:info` that don't ever touch the API (at least not for resolution) as I understand it. Or does the resolver call out to API for this?

**Comment by bjeanes** [comment]
@uhoh-itsmaciek no that resolver is used in `GET (/apps/:id/)?/addons/:identifier`. 

You can test this with the API by hitting something like `GET /apps/<whatevre>/addons/DATABASE_URL`.

**Comment by bjeanes** [comment]
> Or does the resolver call out to API for this?

Yes, it does.

**Comment by uhoh-itsmaciek** [comment]
Ok, excellent.

**Comment by dickeyxxx** [comment]
I need dis.

**Comment by bjeanes** [comment]
lol.

**Pull request merged**
